name: imdb_localization
description: This package contains localization.

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  slang: ^3.19.0
  slang_flutter: ^3.19.0

dev_dependencies:
  thunder_analysis:
    git:
      url: https://github.com/khamidjon/thunder-analysis
  build_runner: ^2.4.5
  slang_build_runner: ^3.7.0